- powershell: |
    @'
    {
      "deploymentName": "Azure DevOps Deployment",
      "eventType": "CUSTOM_DEPLOYMENT",
      "source": "Azure DevOps",
      "title": "Deployment $(Build.BuildNumber)",
      "attachRules": {
        "entityIds": [
          "SERVICE-B295005FEE0D669E"
        ]
      },
      "properties": {
        "dt.event.description": "Deployment triggered from Azure DevOps",
        "BuildId": "$(Build.BuildId)"
      }
    }
    '@ | Out-File "$(Build.SourcesDirectory)\dynatrace-event.json" -Encoding utf8
  displayName: 'Create Dynatrace Event JSON'
